# Legal-RAG: Colab + Qdrant Cloud Version

Phiên bản này được tối ưu để chạy trên Google Colab:
1. Kết nối thẳng tới **Qdrant Cloud**.
2. Sử dụng **GPU (T4)** để tăng tốc độ Embedding (nếu có).
3. Nhập Key trực tiếp trong Cell code.

In [7]:
# @title CẤU HÌNH API KEYS
QDRANT_URL = "https://bc0bb490-f62b-46b6-9863-5e413732dd93.us-west-1-0.aws.cloud.qdrant.io:6333" # @param {type:"string"}
QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.JIE07fUC14MG8NdRmznFquNYS_sfZZ7Y9yEdLfObnAo" # @param {type:"string"}
COLLECTION_NAME = "legal_rag_10000" # @param {type:"string"}

LLM_PROVIDER = "gemini" # @param ["groq", "gemini", "openai"]
LLM_API_KEY = "AIzaSyAYxIzV4OzDa5FufgWJS8T0D8uAyri4Z1Y" # @param {type:"string"}

import os
os.environ["QDRANT_URL"] = QDRANT_URL
os.environ["QDRANT_API_KEY"] = QDRANT_API_KEY
os.environ["GROQ_API_KEY"] = LLM_API_KEY
os.environ["GEMINI_API_KEY"] = LLM_API_KEY
os.environ["OPENAI_API_KEY"] = LLM_API_KEY

print("Cấu hình môi trường hoàn tất.")

Cấu hình môi trường hoàn tất.

# Legal RAG Hybrid Demo Notebook

Notebook nay tap trung vao:
- chunking van ban phap ly xuong muc diem (point-level)
- hybrid retrieval dense + sparse deu dung BGE-M3
- chay local CPU, dung cau hinh key tu file .env
- tai su dung module trong core/ (config, db, llm, nlp)
- co cell uoc tinh thoi gian pipeline tren CPU

In [8]:
%pip install google-genai -q -U qdrant-client datasets pandas scikit-learn accelerate python-dotenv openai ipywidgets sentence-transformers fastembed "FlagEmbedding==1.3.5" "transformers==4.48.3" "huggingface-hub<1.0" "tokenizers<0.22"

In [9]:
from qdrant_client import QdrantClient

if not QDRANT_URL:
    raise ValueError("QDRANT_URL đang trống. Vui lòng nhập Qdrant Cloud URL ở Cell cấu hình.")

client = QdrantClient(url=QDRANT_URL, api_key=QDRANT_API_KEY or None)
print(f"✅ Kết nối Qdrant Cloud thành công: {client.get_collections()}")

✅ Kết nối Qdrant Cloud thành công: collections=[CollectionDescription(name='legal_rag'), CollectionDescription(name='legal_vn_200_docs')]

In [10]:
# Cell 2: local setup (.env), Qdrant, va BGE-M3 cho ca dense + sparse
from __future__ import annotations

import json
import math
import os
import re
import uuid
from pathlib import Path
from typing import Any, Dict, List, Optional

import pandas as pd
import torch  # <-- Bắt buộc thêm import torch để dùng nhận diện GPU
from datasets import load_dataset
from dotenv import load_dotenv
from IPython.display import display
from qdrant_client import QdrantClient, models
from FlagEmbedding import BGEM3FlagModel


# Đã ẩn dòng dưới đây để Pytorch có thể thấy GPU (nếu có)
# os.environ["CUDA_VISIBLE_DEVICES"] = ""
os.environ["TOKENIZERS_PARALLELISM"] = "false"

# 1. Bỏ load_dotenv() vì bạn đã set os.environ ở Cell Cấu hình phía trên rồi
# load_dotenv()

DENSE_MODEL_NAME = os.getenv("LEGAL_DENSE_MODEL", "BAAI/bge-m3")

# 2. Lấy URL và API KEY trực tiếp từ biến môi trường
QDRANT_URL = os.getenv("QDRANT_URL")
if not QDRANT_URL:
    raise ValueError("QDRANT_URL is required. Vui lòng chạy Cell Cấu hình API trước.")

QDRANT_API_KEY = os.getenv("QDRANT_API_KEY")

# 3. Kế thừa biến COLLECTION_NAME từ cell trên (nếu có), không có thì mặc định "legal_rag"
TARGET_COLLECTION = globals().get("COLLECTION_NAME", "legal_rag")

# ========================================================
# ĐOẠN CODE KHỞI TẠO CLIENT
# ========================================================
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

print(f"Using device: {DEVICE}")
print(f"BGE-M3 model: {DENSE_MODEL_NAME}")
print(f"Target Collection: {TARGET_COLLECTION}")

qdrant_client = QdrantClient(
    url=QDRANT_URL,
    api_key=QDRANT_API_KEY,
)
print(f"Qdrant connected to Cloud: {QDRANT_URL}")
# ========================================================
# ========================================================

class LocalBGEHybridEncoder:
    """Use one BGE-M3 model to produce both dense and sparse vectors."""

    def __init__(self, model_name: str = "BAAI/bge-m3", device: str = "cpu"):
        self.model_name = model_name
        self.device = device
        self.model = BGEM3FlagModel(model_name, use_fp16=False, device=device)

    @staticmethod
    def _to_sparse_vector(weights: Dict[str, float]) -> models.SparseVector:
        if not weights:
            return models.SparseVector(indices=[], values=[])
        pairs = [(int(k), float(v)) for k, v in weights.items() if float(v) != 0.0]
        pairs.sort(key=lambda x: x[0])
        return models.SparseVector(
            indices=[idx for idx, _ in pairs],
            values=[val for _, val in pairs],
        )

    def encode_dense(self, texts: List[str], batch_size: int = 8) -> List[List[float]]:
        if isinstance(texts, str):
            texts = [texts]
        outputs = self.model.encode(
            texts,
            batch_size=batch_size,
            max_length=8192,
            return_dense=True,
            return_sparse=False,
            return_colbert_vecs=False,
        )
        dense_vecs = outputs["dense_vecs"]
        return dense_vecs.tolist() if hasattr(dense_vecs, "tolist") else [list(vec) for vec in dense_vecs]

    def encode_sparse_documents(self, texts: List[str], batch_size: int = 8) -> List[models.SparseVector]:
        if isinstance(texts, str):
            texts = [texts]
        outputs = self.model.encode(
            texts,
            batch_size=batch_size,
            max_length=8192,
            return_dense=False,
            return_sparse=True,
            return_colbert_vecs=False,
        )
        lexical_weights = outputs["lexical_weights"]
        return [self._to_sparse_vector(weights) for weights in lexical_weights]

    def encode_query_sparse(self, text: str) -> models.SparseVector:
        return self.encode_sparse_documents([text], batch_size=1)[0]


print("Loading BGE-M3 for dense + sparse...")
hybrid_encoder = LocalBGEHybridEncoder(model_name=DENSE_MODEL_NAME, device=DEVICE)

probe_dense = hybrid_encoder.encode_dense(["kiem tra kich thuoc vector"], batch_size=1)[0]
dense_dim = len(probe_dense)
print(f"Dense embedding dimension: {dense_dim}")

if not qdrant_client.collection_exists(COLLECTION_NAME):
    qdrant_client.create_collection(
        collection_name=COLLECTION_NAME,
        vectors_config={
            "dense": models.VectorParams(
                size=dense_dim,
                distance=models.Distance.COSINE,
                on_disk=True,
            )
        },
        sparse_vectors_config={
            "sparse": models.SparseVectorParams(
                index=models.SparseIndexParams(on_disk=False)
            )
        },
    )
    print(f"Created Qdrant collection: {COLLECTION_NAME}")
else:
    print(f"Qdrant collection already exists: {COLLECTION_NAME}")

# Keep old variable names for compatibility with later cells
embedder = hybrid_encoder
sparse_encoder = hybrid_encoder

print("Local BGE-M3 hybrid encoder is ready (dense + sparse).")

Using device: cuda
BGE-M3 model: BAAI/bge-m3
Target Collection: legal_rag_10000
Qdrant connected to Cloud: https://bc0bb490-f62b-46b6-9863-5e413732dd93.us-west-1-0.aws.cloud.qdrant.io:6333
Loading BGE-M3 for dense + sparse...

Fetching 30 files:   0%|          | 0/30 [00:00<?, ?it/s]

pre tokenize: 100%|██████████| 1/1 [00:00<00:00, 573.78it/s]
You're using a XLMRobertaTokenizerFast tokenizer. Please note that with a fast tokenizer, using the `__call__` method is faster than using a method to encode the text followed by a call to the `pad` method to get a padded encoding.
Inference Embeddings: 100%|██████████| 1/1 [00:00<00:00, 21.45it/s]

Dense embedding dimension: 1024
Created Qdrant collection: legal_rag_10000
Local BGE-M3 hybrid encoder is ready (dense + sparse).

In [35]:
# Cell 3: Gộp nhóm sector đồng nghĩa và lấy 500 docs từ Top 10 Nhóm (mỗi nhóm 50 docs)
print("Dang load metadata/content tu Hugging Face dataset ...")
ds_metadata = load_dataset("th1nhng0/vietnamese-legal-documents", "metadata", split="data")
ds_content = load_dataset("th1nhng0/vietnamese-legal-documents", "content", split="data")

import re
import pandas as pd
from bisect import bisect_left
from typing import Any, List, Dict

def split_sector_list(value: Any) -> List[str]:
    if value is None: return []
    if isinstance(value, list):
        raw_text = ", ".join(str(x) for x in value if str(x).strip())
    else:
        raw_text = str(value).strip()
    if not raw_text or raw_text.lower() == "nan": return []
    parts = re.split(r"\s+-\s+|\s*,\s*", raw_text)
    return sorted(set(part.strip() for part in parts if part and part.strip()))

def contains_sector(sorted_sectors: List[str], target: str) -> bool:
    if not sorted_sectors or not target: return False
    pos = bisect_left(sorted_sectors, target)
    return pos < len(sorted_sectors) and sorted_sectors[pos] == target

df_meta = ds_metadata.to_pandas().copy()
df_meta["id"] = df_meta["id"].astype(str)
df_meta["sector_list"] = df_meta["legal_sectors"].apply(split_sector_list)
df_meta = df_meta[df_meta["sector_list"].map(len) > 0].copy()

# 1. Đếm số lượng từng sector
sector_counts = (
    df_meta.explode("sector_list")["sector_list"]
    .value_counts()
    .reset_index()
)
sector_counts.columns = ["sector", "count"]

# 2. NHÓM CÁC SECTOR CÙNG SỐ LƯỢNG (Nhóm đồng nghĩa)
# Gom các tên sector có cùng giá trị 'count' vào một list
grouped_sectors = (
    sector_counts.groupby("count")["sector"]
    .apply(lambda x: " / ".join(list(x)))
    .reset_index()
)
# Sắp xếp theo số lượng giảm dần
grouped_sectors = grouped_sectors.sort_values("count", ascending=False).reset_index(drop=True)

# 3. CHỌN TOP 10 NHÓM
TOP_K_GROUPS = 10
PER_GROUP_DOCS = 50
target_docs = TOP_K_GROUPS * PER_GROUP_DOCS # 500
seed = 42

top_10_groups = grouped_sectors.head(TOP_K_GROUPS)

print(f"--- Top {TOP_K_GROUPS} Nhóm lĩnh vực sau khi gộp đồng nghĩa ---")
display(top_10_groups)

# 4. LẤY MẪU 50 TÀI LIỆU MỖI NHÓM
selected_ids = []

for idx, row in top_10_groups.iterrows():
    # Lấy danh sách các sector đơn lẻ trong nhóm này
    sectors_in_group = row["sector"].split(" / ")

    # Lọc các doc_id chứa ít nhất 1 sector trong nhóm này
    mask = df_meta["sector_list"].apply(lambda arr: any(s in arr for s in sectors_in_group))
    group_pool = df_meta[mask]["id"].unique()

    # Lấy ngẫu nhiên 50 cái
    sampled = pd.Series(group_pool).sample(n=min(PER_GROUP_DOCS, len(group_pool)), random_state=seed).tolist()
    selected_ids.extend(sampled)

# 5. Làm sạch và bổ sung (Deduplicate & Fill)
selected_ids = list(dict.fromkeys(selected_ids))

if len(selected_ids) < target_docs:
    # Nếu bị trùng lặp giữa các nhóm dẫn đến thiếu, lấy bù từ pool của Top 10 nhóm
    all_top_sectors = " / ".join(top_10_groups["sector"].tolist()).split(" / ")
    remaining_mask = df_meta["sector_list"].apply(lambda arr: any(s in arr for s in all_top_sectors))
    remaining_pool = df_meta[remaining_mask & ~df_meta["id"].isin(selected_ids)]["id"].unique()

    if len(remaining_pool) > 0:
        fill_n = min(target_docs - len(selected_ids), len(remaining_pool))
        fill_ids = pd.Series(remaining_pool).sample(n=fill_n, random_state=seed).tolist()
        selected_ids.extend(fill_ids)

# Cắt đúng 500
if len(selected_ids) > target_docs:
    selected_ids = pd.Series(selected_ids).sample(n=target_docs, random_state=seed).tolist()

# Tạo DataFrame kết quả
df_500 = (
    df_meta[df_meta["id"].isin(set(selected_ids))]
    .drop_duplicates(subset="id")
    .sample(frac=1, random_state=seed)
    .reset_index(drop=True)
)

# Filter Dataset chính thức
valid_ids_500 = set(df_500["id"].astype(str))
ds_metadata_500 = ds_metadata.filter(lambda row: str(row["id"]) in valid_ids_500)
ds_content_500 = ds_content.filter(lambda row: str(row["id"]) in valid_ids_500)

metadata_by_id = {str(row["id"]): row for row in ds_metadata_500}
content_by_id = {str(row["id"]): row for row in ds_content_500}

print(f"\n✅ Tong so van ban da chon: {len(ds_content_500)}")

# Thống kê lại phân bổ để kiểm tra
print("\n--- Phan bo du lieu trong 500 sample (Theo nhom gop) ---")
final_dist = df_500.explode("sector_list")["sector_list"].value_counts().head(15)
display(final_dist.to_frame("count_in_sample"))

Dang load metadata/content tu Hugging Face dataset ...
--- Top 10 Nhóm lĩnh vực sau khi gộp đồng nghĩa ---

    count                   sector
0  164069        Bộ máy hành chính
1   66223      Lệ Phí / Phí / Thuế
2   58529       Tài chính nhà nước
3   54117         Văn hóa / Xã hội
4   40465           Xuất nhập khẩu
5   37584  Môi trường / Tài nguyên
6   36834                 Xây dựng
7   36829                   Đô thị
8   36192               Thương mại
9   34793             Bất động sản

Filter:   0%|          | 0/518255 [00:00<?, ? examples/s]

Filter:   0%|          | 0/518255 [00:00<?, ? examples/s]

✅ Tong so van ban da chon: 500

--- Phan bo du lieu trong 500 sample (Theo nhom gop) ---

                    count_in_sample
sector_list
Bộ máy hành chính               121
Xây dựng                        114
Đô thị                          114
Tài chính nhà nước               86
Lệ Phí                           79
Phí                              79
Thuế                             79
Xuất nhập khẩu                   76
Văn hóa                          75
Xã hội                           75
Thương mại                       71
Bất động sản                     70
Môi trường                       64
Tài nguyên                       64
Đầu tư                           19

In [38]:
# Cell 4: in thu 1 van ban trong tap test de kiem tra
target_id = str(df_500.iloc[0]["id"])
metadata_raw = metadata_by_id[target_id]
content_raw = content_by_id[target_id]["content"]

print(f"Target test document id: {target_id}")
print("=" * 120)
print("METADATA")
print("=" * 120)
for key, value in metadata_raw.items():
    if key != "id":
        print(f"{key}: {value}")

print("\n" + "=" * 120)
print("RAW CONTENT")
print("=" * 120)
print(content_raw)

Target test document id: 247335
========================================================================================================================
METADATA
========================================================================================================================
document_number: 10666/TCHQ-ĐTCBL
title: Công văn 10666/TCHQ-ĐTCBL năm 2014 tăng cường kiểm tra, kiểm soát gia cầm, sản phẩm gia cầm nhập khẩu, vận chuyển trái phép qua biên giới do Tổng cục Hải quan ban hành
url: https://thuvienphapluat.vn/cong-van/Thuong-mai/Cong-van-10666-TCHQ-DTCBL-2014-kiem-soat-gia-cam-san-pham-gia-cam-nhap-khau-van-chuyen-trai-phep-qua-bien-gioi-247335.aspx
legal_type: Công văn
legal_sectors: Thương mại, Xuất nhập khẩu, Bộ máy hành chính
issuing_authority: Tổng cục Hải quan
issuance_date: 28/08/2014
signers: Nguyễn Văn Cẩn:489

========================================================================================================================
RAW CONTENT
========================================================================================================================
BỘ TÀI CHÍNH TỔNG CỤC HẢI QUAN  | CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM Độc lập - Tự do - Hạnh phúc
Số: 10666/TCHQ-ĐTCBL V/v tăng cường kiểm tra, kiểm soát gia cầm, sản phẩm gia cầm nhập khẩu, vận chuyển trái phép qua biên giới. | Hà Nội, ngày 28 tháng 08 năm 2014

Kính gửi: | - Cục Hải quan các tỉnh, thành phố; - Cục Điều tra chống buôn lậu.

Trong thời gian gần đây, hoạt động vận chuyển, kinh doanh gia cầm, các sản phẩm gia cầm trái phép có dấu hiệu phức tạp trở lại. Nhằm chủ động trong việc đấu tranh, bắt giữ các hành vi vi phạm cũng như phòng, chống dịch cúm gia cầm lây lan qua biên giới, đặc biệt là chủng cúm gia cầm mới A/H5N6, Tổng cục Hải quan yêu cầu các đơn vị triển khai một số công việc sau

1. Quán triệt và triển khai thực hiện Công văn số 8035/BCT-QLTT ngày 20/8/2014 của Bộ Công thương (khai thác trên mạng Net Office) và các văn bản liên quan đến phòng, chống buôn lậu, vận chuyển trái phép gia cầm qua biên giới.

Tiếp tục thực hiện Quyết định số 2088/QĐ-TTg ngày 27/12/2012 của Thủ tướng Chính phủ về việc phê duyệt Đề án phòng ngừa, ngăn chặn vận chuyển và kinh doanh gia cầm, sản phẩm gia cầm nhập khẩu trái phép; Công văn số 1870/TCHQ-ĐTCBL ngày 10/4/2013; Công văn số 2060/TCHQ-ĐTCBL ngày 22/4/2013; Công văn số 1611/TCHQ-ĐTCBL ngày 19/02/2014 về việc tăng cường kiểm tra, kiểm soát chặt chẽ gia cầm, sản phẩm gia cầm nhập lậu, chủ động phòng, chống lây lan dịch cúm gia cầm qua biên giới; Công văn số 419/ĐTCBL-P1 ngày 03/5/2013 về việc thực hiện chế độ báo cáo nhanh đối với gia cầm, sản phẩm gia cầm nhập khẩu, vận chuyển trái phép qua biên giới bị bắt giữ, xử lý.

2. Triển khai kịp thời các chỉ đạo của Chính phủ, Bộ Tài chính, Ủy ban Nhân dân các tỉnh, thành phố, Ban chỉ đạo 389 địa phương về công tác phòng, chống buôn lậu, vận chuyển trái phép gia cầm, sản phẩm từ gia cầm qua biên giới.

3. Cục trưởng Cục Hải quan tỉnh, thành phố đôn đốc, chỉ đạo các đơn vị trực thuộc căn cứ nhiệm vụ, quyền hạn và tình hình buôn lậu trên địa bàn quản lý của đơn vị tăng cường các biện pháp nghiệp vụ kiểm soát hải quan để xác định phương thức, thủ đoạn, đường dây, ổ nhóm, đối tượng buôn bán, vận chuyển trái phép gia cầm, sản phẩm gia cầm trên địa bàn hoạt động hải quan; chủ động xây dựng kế hoạch, đấu tranh có trọng điểm, có hiệu quả, kiên quyết không để xảy ra vụ việc buôn lậu nghiêm trọng tại địa bàn quản lý của đơn vị.

4. Tổ chức lực lượng, chủ động phối hợp với các lực lượng chức năng khác như Quản lý thị trường, Biên phòng, Công an, Kiểm dịch tại cửa khẩu ... và chính quyền địa phương để trao đổi thông tin, đấu tranh phát hiện, bắt giữ, xử lý các hành vi vi phạm.

5. Tăng cường công tác tuyên truyền, vận động người dân tham gia tố giác các hành vi vi phạm pháp luật, không tham gia, bao che, tiếp tay cho các đối tượng vi phạm.

6. Thực hiện chế độ báo cáo định kỳ hoặc đột xuất về kết quả công tác đấu tranh phòng, chống buôn lậu, vận chuyển trái phép gia cầm, sản phẩm từ gia cầm qua biên giới về Tổng cục Hải quan (qua Cục Điều tra chống buôn lậu) theo địa chỉ:

Cục Điều tra chống buôn lậu - Tổng cục Hải quan

Lô E3, Đường Dương Đình Nghệ, Phường Yên Hòa, Cầu Giấy, Hà Nội.

Tel: 04.39440833 (máy lẻ: 9813) Fax: 04.39440633

Email: cbl-thammuu@customs.gov.vn

Đề nghị Cục trưởng các Cục Hải quan tỉnh, thành phố và Cục trưởng Cục Điều tra chống buôn lậu nghiêm túc thực hiện./.

Nơi nhận: - Như trên; - Thứ trưởng Đỗ Hoàng Anh Tuấn (để b/c); - Bộ Công thương (để b/c); - TCT Nguyễn Ngọc Túc (để b/c); - Lưu: VT, ĐTCBL (03b). | KT. TỔNG CỤC TRƯỞNG PHÓ TỔNG CỤC TRƯỞNG Nguyễn Văn Cẩn

In [40]:
# Cell 5: chunker phap ly nang cao -> tach can cu / dieu / khoan / diem / phu luc + Fallback Chunking
def compact_whitespace(text: str) -> str:
    return re.sub(r"[ \t]+", " ", str(text or "")).strip()

class AdvancedLegalChunker:
    def __init__(self, appendix_chunk_size: int = 1000, max_chunk_size: int = 1500):
        self.appendix_chunk_size = appendix_chunk_size
        self.max_chunk_size = max_chunk_size # Thêm giới hạn ký tự an toàn cho 1 chunk
        self.appendix_pattern = re.compile(r"(?im)^\s*(PHU LUC|PHỤ LỤC|DANH MUC|DANH MỤC)\b.*$")
        self.chapter_pattern = re.compile(r"(?im)^\s*(Chương\s+[IVXLCDM0-9]+)\s*(.*)$")
        self.article_pattern = re.compile(r"(?im)^\s*(Điều\s+\d+[A-Za-z0-9\/\-]*)[\.\:\-]?\s*(.*)$")
        self.clause_pattern = re.compile(
            r"(?im)^\s*(Khoản\s+\d+[\.\:\-]?)\s*(.*)$|^\s*(\d+[\.\)])\s*(.*)$"
        )
        self.point_pattern = re.compile(
            r"(?im)^[ \t]*(Điểm\s+[a-zđ]+[\.\:\-]?)\s*(.*)$|^[ \t]*([a-zđ][\.\)])\s*(.*)$"
        )

    def _normalize_metadata(self, metadata):
        data = dict(metadata)
        data["id"] = str(data.get("id", ""))
        data["legal_sectors_list"] = parse_sector_list(data.get("legal_sectors"))
        data["legal_sectors_text"] = "; ".join(data["legal_sectors_list"])
        data["signer"] = data.get("signer") or data.get("signers") or ""
        return data

    def _build_metadata_header(self, metadata, reference_tag, is_appendix, article_ref=None, clause_ref=None, chapter_ref=None, point_ref=None):
        header_lines = [
            "[LEGAL HEADER]",
            f"- Title: {metadata.get('title', 'N/A')}",
            f"- Document number: {metadata.get('document_number', 'N/A')}",
            f"- Legal type: {metadata.get('legal_type', 'N/A')}",
            f"- Issuing authority: {metadata.get('issuing_authority', 'N/A')}",
            f"- Legal sectors: {metadata.get('legal_sectors_text', metadata.get('legal_sectors', 'N/A'))}",
            f"- Reference tag: {reference_tag}",
            f"- Chapter: {chapter_ref or 'N/A'}",
            f"- Article: {article_ref or 'N/A'}",
            f"- Clause: {clause_ref or 'N/A'}",
            f"- Point: {point_ref or 'N/A'}",
            f"- Is appendix: {is_appendix}",
            "",
        ]
        return "\n".join(header_lines)

    def _build_citation(self, metadata, chapter_ref, article_ref, clause_ref, is_appendix, appendix_part=None, point_ref=None):
        pieces = [metadata.get("document_number") or metadata.get("title") or "Van ban"]
        if chapter_ref: pieces.append(chapter_ref)
        if article_ref: pieces.append(article_ref)
        if clause_ref: pieces.append(clause_ref)
        if point_ref: pieces.append(point_ref)
        if is_appendix and appendix_part: pieces.append(appendix_part)
        return " | ".join([piece for piece in pieces if piece])

    # HÀM MỚI: Tự động chia nhỏ text nếu bị quá giới hạn (Dành cho Công văn / Phần mở đầu dài)
    def _chunk_by_length(self, text: str) -> List[str]:
        if len(text) <= self.max_chunk_size:
            return [text]

        lines = text.split('\n')
        chunks = []
        current_chunk = []
        current_len = 0

        for line in lines:
            line = line.strip()
            if not line: continue

            if current_len + len(line) > self.max_chunk_size and current_chunk:
                chunks.append("\n".join(current_chunk))
                current_chunk = [line]
                current_len = len(line)
            else:
                current_chunk.append(line)
                current_len += len(line) + 1

        if current_chunk:
            chunks.append("\n".join(current_chunk))
        return chunks

    def _split_main_and_appendix(self, content):
        match = self.appendix_pattern.search(content)
        if match:
            return content[: match.start()].strip(), content[match.start() :].strip()
        return content.strip(), ""

    def _split_articles(self, main_text):
        intro_lines = []
        articles = []
        current_article = None
        current_chapter = None

        for raw_line in main_text.splitlines():
            line = raw_line.rstrip()

            if not line.strip():
                if current_article is None: intro_lines.append("")
                else: current_article["lines"].append("")
                continue

            chapter_match = self.chapter_pattern.match(line)
            if chapter_match:
                current_chapter = compact_whitespace(line)
                if current_article is None: intro_lines.append(line)
                else: current_article["lines"].append(line)
                continue

            article_match = self.article_pattern.match(line)
            if article_match:
                if current_article is not None:
                    articles.append(current_article)

                current_article = {
                    "chapter_ref": current_chapter,
                    "article_ref": compact_whitespace(article_match.group(1)),
                    "article_title": compact_whitespace(article_match.group(2)),
                    "lines": [line],
                }
                continue

            if current_article is None:
                intro_lines.append(line)
            else:
                current_article["lines"].append(line)

        if current_article is not None:
            articles.append(current_article)

        return "\n".join(intro_lines).strip(), articles

    def _split_clauses(self, article):
        full_article_text = "\n".join(article["lines"]).strip()
        body_lines = article["lines"][1:] if len(article["lines"]) > 1 else []
        clauses = []
        current_clause = None

        for raw_line in body_lines:
            line = raw_line.rstrip()
            clause_match = self.clause_pattern.match(line)

            if clause_match:
                if current_clause is not None: clauses.append(current_clause)
                clause_ref = compact_whitespace(clause_match.group(1) or clause_match.group(3))
                clause_tail = compact_whitespace(clause_match.group(2) or clause_match.group(4))
                current_clause = {"clause_ref": clause_ref, "lines": [f"{clause_ref} {clause_tail}".strip()]}
                continue

            if current_clause is None:
                if line.strip(): current_clause = {"clause_ref": None, "lines": [line]}
            else:
                current_clause["lines"].append(line)

        if current_clause is not None: clauses.append(current_clause)
        if not clauses: clauses = [{"clause_ref": None, "lines": article["lines"]}]

        return full_article_text, clauses

    def _split_points(self, clause):
        body_lines = clause["lines"]
        points = []
        current_point = None

        for raw_line in body_lines:
            line = raw_line.rstrip()
            point_match = self.point_pattern.match(line)

            if point_match:
                if current_point is not None: points.append(current_point)
                point_ref = compact_whitespace(point_match.group(1) or point_match.group(3))
                point_tail = compact_whitespace(point_match.group(2) or point_match.group(4))
                current_point = {"point_ref": point_ref, "lines": [f"{point_ref} {point_tail}".strip()]}
                continue

            if current_point is None:
                if line.strip(): current_point = {"point_ref": None, "lines": [line]}
            else:
                current_point["lines"].append(line)

        if current_point is not None: points.append(current_point)
        if not points: points = [{"point_ref": None, "lines": clause["lines"]}]

        return points

    def _appendix_chunks(self, appendix_text, metadata, doc_id):
        # Giữ nguyên logic cũ của phụ lục... (để tránh rườm rà, tôi rút gọn logic gốc của bạn vào đây)
        chunks = []
        if not appendix_text: return chunks

        # Áp dụng luôn Fallback Chunking cho phụ lục nếu nó quá dài
        app_chunks = self._chunk_by_length(appendix_text)
        for part_idx, chunk_text in enumerate(app_chunks, start=1):
            header_app = self._build_metadata_header(
                metadata=metadata, reference_tag=f"Phu luc - P{part_idx}", is_appendix=True, article_ref="Phu luc"
            )
            citation = self._build_citation(
                metadata=metadata, chapter_ref=None, article_ref="Phu luc", clause_ref=None, is_appendix=True, appendix_part=f"P{part_idx}"
            )
            chunks.append({
                "chunk_id": f"{doc_id}::appendix::{part_idx}",
                "text_to_embed": f"{header_app}[PHAN {part_idx}]\n{chunk_text.strip()}",
                "reference_tag": f"Phu luc - P{part_idx}",
                "unit_text": chunk_text.strip(),
                "metadata": {
                    **metadata, "is_appendix": True, "chapter_ref": None, "article_id": f"{doc_id}::appendix::{part_idx}",
                    "article_ref": "Phu luc", "article_title": "Phu luc", "clause_ref": f"P{part_idx}", "point_ref": None,
                    "parent_article_text": chunk_text.strip(), "reference_citation": citation,
                },
            })
        return chunks

    def process_document(self, content, metadata):
        metadata = self._normalize_metadata(metadata)
        content = str(content or "").replace("\r\n", "\n").strip()
        doc_id = metadata.get("id") or str(uuid.uuid4())
        chunks = []

        main_text, appendix_text = self._split_main_and_appendix(content)
        intro_text, articles = self._split_articles(main_text)

        # XỬ LÝ PHẦN MỞ ĐẦU HOẶC CÔNG VĂN (Kích hoạt Fallback Chunking)
        if intro_text:
            intro_sub_chunks = self._chunk_by_length(intro_text)
            for idx, sub_text in enumerate(intro_sub_chunks):
                article_id = f"{doc_id}::preamble"
                ref_tag = "Noi dung" if len(intro_sub_chunks) == 1 else f"Noi dung (P{idx+1})"

                citation = self._build_citation(
                    metadata=metadata, chapter_ref=None, article_ref=ref_tag, clause_ref=None, is_appendix=False
                )
                header = self._build_metadata_header(
                    metadata=metadata, reference_tag=ref_tag, is_appendix=False, article_ref=ref_tag
                )
                chunks.append({
                    "chunk_id": f"{article_id}::{idx}",
                    "text_to_embed": f"{header}[NOI DUNG]\n{sub_text}",
                    "reference_tag": ref_tag,
                    "unit_text": sub_text,
                    "metadata": {
                        **metadata, "is_appendix": False, "chapter_ref": None, "article_id": article_id,
                        "article_ref": ref_tag, "article_title": "Noi dung", "clause_ref": None, "point_ref": None,
                        "parent_article_text": sub_text, "reference_citation": citation,
                    },
                })

        # XỬ LÝ ĐIỀU / KHOẢN / ĐIỂM (Như cũ, nhưng an toàn hơn)
        for article_index, article in enumerate(articles, start=1):
            article_id = f"{doc_id}::article::{article_index}"
            full_article_text, clause_entries = self._split_clauses(article)
            article_context = (f"{article['chapter_ref']}\n{full_article_text}".strip() if article.get("chapter_ref") else full_article_text)

            for clause_index, clause in enumerate(clause_entries, start=1):
                clause_ref = clause["clause_ref"]
                point_entries = self._split_points(clause)

                for point_index, point in enumerate(point_entries, start=1):
                    point_ref = point["point_ref"]
                    unit_text = "\n".join(point["lines"]).strip()

                    # Nếu Điểm/Khoản này vẫn bị viết quá dài (hiếm nhưng có), băm nhỏ nó ra
                    point_sub_chunks = self._chunk_by_length(unit_text)

                    for sub_idx, sub_unit_text in enumerate(point_sub_chunks):
                        tag_parts = [article["article_ref"]]
                        if clause_ref: tag_parts.append(clause_ref)
                        if point_ref: tag_parts.append(point_ref)
                        if len(point_sub_chunks) > 1: tag_parts.append(f"P{sub_idx+1}")

                        reference_tag = " - ".join(tag_parts)
                        citation = self._build_citation(
                            metadata=metadata, chapter_ref=article.get("chapter_ref"), article_ref=article["article_ref"],
                            clause_ref=clause_ref, is_appendix=False, point_ref=point_ref
                        )
                        header = self._build_metadata_header(
                            metadata=metadata, reference_tag=reference_tag, is_appendix=False, article_ref=article["article_ref"],
                            clause_ref=clause_ref, chapter_ref=article.get("chapter_ref"), point_ref=point_ref
                        )

                        chunks.append({
                            "chunk_id": f"{article_id}::c{clause_index}::p{point_index}::{sub_idx}",
                            "text_to_embed": f"{header}[DIEU CHA]\n{article_context[:1000]}...\n\n[DIEM TRUY HOI]\n{sub_unit_text}",
                            "reference_tag": reference_tag,
                            "unit_text": sub_unit_text,
                            "metadata": {
                                **metadata, "is_appendix": False, "chapter_ref": article.get("chapter_ref"), "article_id": article_id,
                                "article_ref": article["article_ref"], "article_title": article.get("article_title"),
                                "clause_ref": clause_ref, "point_ref": point_ref, "parent_article_text": article_context,
                                "reference_citation": citation,
                            },
                        })

        chunks.extend(self._appendix_chunks(appendix_text, metadata, doc_id))
        return chunks

chunker = AdvancedLegalChunker()
result_chunks = chunker.process_document(content_raw, metadata_raw)

print(f"KIEM TRA document id: {target_id}")
print(f"Tong so chunk sinh ra: {len(result_chunks)}")
print("-" * 140)

for idx, chunk in enumerate(result_chunks, start=1):
    meta = chunk["metadata"]
    preview = chunk["text_to_embed"].replace("\n", " | ")
    print(f"[{idx:03d}] len={len(chunk['text_to_embed'])} | ref={chunk['reference_tag']} | {preview}...")

KIEM TRA document id: 247335
Tong so chunk sinh ra: 3
--------------------------------------------------------------------------------------------------------------------------------------------
[001] len=1415 | ref=Noi dung (P1) | [LEGAL HEADER] | - Title: Công văn 10666/TCHQ-ĐTCBL năm 2014 tăng cường kiểm tra, kiểm soát gia cầm, sản phẩm gia cầm nhập khẩu, vận chuyển trái phép qua biên giới do Tổng cục Hải quan ban hành | - Document number: 10666/TCHQ-ĐTCBL | - Legal type: Công văn | - Issuing authority: Tổng cục Hải quan | - Legal sectors: Bộ máy hành chính; Thương mại; Xuất nhập khẩu | - Reference tag: Noi dung (P1) | - Chapter: N/A | - Article: Noi dung (P1) | - Clause: N/A | - Point: N/A | - Is appendix: False | [NOI DUNG] | BỘ TÀI CHÍNH TỔNG CỤC HẢI QUAN  | CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM Độc lập - Tự do - Hạnh phúc | Số: 10666/TCHQ-ĐTCBL V/v tăng cường kiểm tra, kiểm soát gia cầm, sản phẩm gia cầm nhập khẩu, vận chuyển trái phép qua biên giới. | Hà Nội, ngày 28 tháng 08 năm 2014 | Kính gửi: | - Cục Hải quan các tỉnh, thành phố; - Cục Điều tra chống buôn lậu. | Trong thời gian gần đây, hoạt động vận chuyển, kinh doanh gia cầm, các sản phẩm gia cầm trái phép có dấu hiệu phức tạp trở lại. Nhằm chủ động trong việc đấu tranh, bắt giữ các hành vi vi phạm cũng như phòng, chống dịch cúm gia cầm lây lan qua biên giới, đặc biệt là chủng cúm gia cầm mới A/H5N6, Tổng cục Hải quan yêu cầu các đơn vị triển khai một số công việc sau | 1. Quán triệt và triển khai thực hiện Công văn số 8035/BCT-QLTT ngày 20/8/2014 của Bộ Công thương (khai thác trên mạng Net Office) và các văn bản liên quan đến phòng, chống buôn lậu, vận chuyển trái phép gia cầm qua biên giới....
[002] len=1895 | ref=Noi dung (P2) | [LEGAL HEADER] | - Title: Công văn 10666/TCHQ-ĐTCBL năm 2014 tăng cường kiểm tra, kiểm soát gia cầm, sản phẩm gia cầm nhập khẩu, vận chuyển trái phép qua biên giới do Tổng cục Hải quan ban hành | - Document number: 10666/TCHQ-ĐTCBL | - Legal type: Công văn | - Issuing authority: Tổng cục Hải quan | - Legal sectors: Bộ máy hành chính; Thương mại; Xuất nhập khẩu | - Reference tag: Noi dung (P2) | - Chapter: N/A | - Article: Noi dung (P2) | - Clause: N/A | - Point: N/A | - Is appendix: False | [NOI DUNG] | Tiếp tục thực hiện Quyết định số 2088/QĐ-TTg ngày 27/12/2012 của Thủ tướng Chính phủ về việc phê duyệt Đề án phòng ngừa, ngăn chặn vận chuyển và kinh doanh gia cầm, sản phẩm gia cầm nhập khẩu trái phép; Công văn số 1870/TCHQ-ĐTCBL ngày 10/4/2013; Công văn số 2060/TCHQ-ĐTCBL ngày 22/4/2013; Công văn số 1611/TCHQ-ĐTCBL ngày 19/02/2014 về việc tăng cường kiểm tra, kiểm soát chặt chẽ gia cầm, sản phẩm gia cầm nhập lậu, chủ động phòng, chống lây lan dịch cúm gia cầm qua biên giới; Công văn số 419/ĐTCBL-P1 ngày 03/5/2013 về việc thực hiện chế độ báo cáo nhanh đối với gia cầm, sản phẩm gia cầm nhập khẩu, vận chuyển trái phép qua biên giới bị bắt giữ, xử lý. | 2. Triển khai kịp thời các chỉ đạo của Chính phủ, Bộ Tài chính, Ủy ban Nhân dân các tỉnh, thành phố, Ban chỉ đạo 389 địa phương về công tác phòng, chống buôn lậu, vận chuyển trái phép gia cầm, sản phẩm từ gia cầm qua biên giới. | 3. Cục trưởng Cục Hải quan tỉnh, thành phố đôn đốc, chỉ đạo các đơn vị trực thuộc căn cứ nhiệm vụ, quyền hạn và tình hình buôn lậu trên địa bàn quản lý của đơn vị tăng cường các biện pháp nghiệp vụ kiểm soát hải quan để xác định phương thức, thủ đoạn, đường dây, ổ nhóm, đối tượng buôn bán, vận chuyển trái phép gia cầm, sản phẩm gia cầm trên địa bàn hoạt động hải quan; chủ động xây dựng kế hoạch, đấu tranh có trọng điểm, có hiệu quả, kiên quyết không để xảy ra vụ việc buôn lậu nghiêm trọng tại địa bàn quản lý của đơn vị....
[003] len=1650 | ref=Noi dung (P3) | [LEGAL HEADER] | - Title: Công văn 10666/TCHQ-ĐTCBL năm 2014 tăng cường kiểm tra, kiểm soát gia cầm, sản phẩm gia cầm nhập khẩu, vận chuyển trái phép qua biên giới do Tổng cục Hải quan ban hành | - Document number: 10666/TCHQ-ĐTCBL | - Legal type: Công văn | - Issuing authority: Tổng cục Hải quan | - Legal sectors: Bộ máy hành chính; Thương mại; Xuất nhập khẩu | - Reference tag: Noi dung (P3) | - Chapter: N/A | - Article: Noi dung (P3) | - Clause: N/A | - Point: N/A | - Is appendix: False | [NOI DUNG] | 4. Tổ chức lực lượng, chủ động phối hợp với các lực lượng chức năng khác như Quản lý thị trường, Biên phòng, Công an, Kiểm dịch tại cửa khẩu ... và chính quyền địa phương để trao đổi thông tin, đấu tranh phát hiện, bắt giữ, xử lý các hành vi vi phạm. | 5. Tăng cường công tác tuyên truyền, vận động người dân tham gia tố giác các hành vi vi phạm pháp luật, không tham gia, bao che, tiếp tay cho các đối tượng vi phạm. | 6. Thực hiện chế độ báo cáo định kỳ hoặc đột xuất về kết quả công tác đấu tranh phòng, chống buôn lậu, vận chuyển trái phép gia cầm, sản phẩm từ gia cầm qua biên giới về Tổng cục Hải quan (qua Cục Điều tra chống buôn lậu) theo địa chỉ: | Cục Điều tra chống buôn lậu - Tổng cục Hải quan | Lô E3, Đường Dương Đình Nghệ, Phường Yên Hòa, Cầu Giấy, Hà Nội. | Tel: 04.39440833 (máy lẻ: 9813) Fax: 04.39440633 | Email: cbl-thammuu@customs.gov.vn | Đề nghị Cục trưởng các Cục Hải quan tỉnh, thành phố và Cục trưởng Cục Điều tra chống buôn lậu nghiêm túc thực hiện./. | Nơi nhận: - Như trên; - Thứ trưởng Đỗ Hoàng Anh Tuấn (để b/c); - Bộ Công thương (để b/c); - TCT Nguyễn Ngọc Túc (để b/c); - Lưu: VT, ĐTCBL (03b). | KT. TỔNG CỤC TRƯỞNG PHÓ TỔNG CỤC TRƯỞNG Nguyễn Văn Cẩn...

In [41]:
# Cell 5.1: In chi tiết cấu trúc (Anatomy) của các chunk đầu tiên
import json

print(f"=== CHI TIẾT KẾT QUẢ CHUNKING CHO VĂN BẢN: {target_id} ===")
print(f"Tổng số chunk được tạo ra: {len(result_chunks)}\n")

# Lấy 2 chunk đầu tiên để kiểm tra (Hoặc bạn có thể đổi thành result_chunks[0:1] nếu chỉ muốn xem chunk đầu)
chunks_to_inspect = result_chunks[:2]

for i, chunk in enumerate(chunks_to_inspect):
    print("=" * 100)
    print(f" CHUNK [{i}] - {chunk['reference_tag']}")
    print("=" * 100)

    # 1. Hiển thị Text to Embed (Dữ liệu sẽ bị biến thành mảng số Vector)
    print("\n[1] VĂN BẢN ĐỂ NHÚNG (Text to Embed - Vector model sẽ đọc cái này):")
    print("-" * 60)
    print(chunk["text_to_embed"])
    print("-" * 60)

    # 2. Hiển thị Unit Text (Đoạn text nhỏ nhất để match)
    print("\n[2] VĂN BẢN MẢNH (Unit Text / Child Chunk):")
    print("-" * 60)
    print(chunk["unit_text"])
    print("-" * 60)

    # 3. Hiển thị Parent Context (Đoạn text to chứa đoạn text nhỏ)
    print("\n[3] NGỮ CẢNH ĐIỀU LUẬT (Parent Article Text - Sẽ đưa cho LLM đọc):")
    print("-" * 60)
    print(chunk["metadata"].get("parent_article_text", "Không có"))
    print("-" * 60)

    # 4. Hiển thị Metadata sẽ được đẩy lên Qdrant Payload
    print("\n[4] METADATA (Sẽ đẩy lên Qdrant để Filter và Rerank):")
    print("-" * 60)
    # Trích xuất một số key quan trọng để in cho đỡ rối mắt
    meta = chunk['metadata']
    meta_preview = {
        "article_id": meta.get("article_id"),
        "chapter_ref": meta.get("chapter_ref"),
        "article_ref": meta.get("article_ref"),
        "clause_ref": meta.get("clause_ref"),
        "point_ref": meta.get("point_ref"),
        "reference_citation": meta.get("reference_citation"),
        "is_appendix": meta.get("is_appendix"),
        "legal_sectors_list": meta.get("legal_sectors_list")
    }
    print(json.dumps(meta_preview, indent=4, ensure_ascii=False))
    print("\n" + "*" * 100 + "\n")

=== CHI TIẾT KẾT QUẢ CHUNKING CHO VĂN BẢN: 247335 ===
Tổng số chunk được tạo ra: 3

====================================================================================================
 CHUNK [0] - Noi dung (P1)
====================================================================================================

[1] VĂN BẢN ĐỂ NHÚNG (Text to Embed - Vector model sẽ đọc cái này):
------------------------------------------------------------
[LEGAL HEADER]
- Title: Công văn 10666/TCHQ-ĐTCBL năm 2014 tăng cường kiểm tra, kiểm soát gia cầm, sản phẩm gia cầm nhập khẩu, vận chuyển trái phép qua biên giới do Tổng cục Hải quan ban hành
- Document number: 10666/TCHQ-ĐTCBL
- Legal type: Công văn
- Issuing authority: Tổng cục Hải quan
- Legal sectors: Bộ máy hành chính; Thương mại; Xuất nhập khẩu
- Reference tag: Noi dung (P1)
- Chapter: N/A
- Article: Noi dung (P1)
- Clause: N/A
- Point: N/A
- Is appendix: False
[NOI DUNG]
BỘ TÀI CHÍNH TỔNG CỤC HẢI QUAN  | CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM Độc lập - Tự do - Hạnh phúc
Số: 10666/TCHQ-ĐTCBL V/v tăng cường kiểm tra, kiểm soát gia cầm, sản phẩm gia cầm nhập khẩu, vận chuyển trái phép qua biên giới. | Hà Nội, ngày 28 tháng 08 năm 2014
Kính gửi: | - Cục Hải quan các tỉnh, thành phố; - Cục Điều tra chống buôn lậu.
Trong thời gian gần đây, hoạt động vận chuyển, kinh doanh gia cầm, các sản phẩm gia cầm trái phép có dấu hiệu phức tạp trở lại. Nhằm chủ động trong việc đấu tranh, bắt giữ các hành vi vi phạm cũng như phòng, chống dịch cúm gia cầm lây lan qua biên giới, đặc biệt là chủng cúm gia cầm mới A/H5N6, Tổng cục Hải quan yêu cầu các đơn vị triển khai một số công việc sau
1. Quán triệt và triển khai thực hiện Công văn số 8035/BCT-QLTT ngày 20/8/2014 của Bộ Công thương (khai thác trên mạng Net Office) và các văn bản liên quan đến phòng, chống buôn lậu, vận chuyển trái phép gia cầm qua biên giới.
------------------------------------------------------------

[2] VĂN BẢN MẢNH (Unit Text / Child Chunk):
------------------------------------------------------------
BỘ TÀI CHÍNH TỔNG CỤC HẢI QUAN  | CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM Độc lập - Tự do - Hạnh phúc
Số: 10666/TCHQ-ĐTCBL V/v tăng cường kiểm tra, kiểm soát gia cầm, sản phẩm gia cầm nhập khẩu, vận chuyển trái phép qua biên giới. | Hà Nội, ngày 28 tháng 08 năm 2014
Kính gửi: | - Cục Hải quan các tỉnh, thành phố; - Cục Điều tra chống buôn lậu.
Trong thời gian gần đây, hoạt động vận chuyển, kinh doanh gia cầm, các sản phẩm gia cầm trái phép có dấu hiệu phức tạp trở lại. Nhằm chủ động trong việc đấu tranh, bắt giữ các hành vi vi phạm cũng như phòng, chống dịch cúm gia cầm lây lan qua biên giới, đặc biệt là chủng cúm gia cầm mới A/H5N6, Tổng cục Hải quan yêu cầu các đơn vị triển khai một số công việc sau
1. Quán triệt và triển khai thực hiện Công văn số 8035/BCT-QLTT ngày 20/8/2014 của Bộ Công thương (khai thác trên mạng Net Office) và các văn bản liên quan đến phòng, chống buôn lậu, vận chuyển trái phép gia cầm qua biên giới.
------------------------------------------------------------

[3] NGỮ CẢNH ĐIỀU LUẬT (Parent Article Text - Sẽ đưa cho LLM đọc):
------------------------------------------------------------
BỘ TÀI CHÍNH TỔNG CỤC HẢI QUAN  | CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM Độc lập - Tự do - Hạnh phúc
Số: 10666/TCHQ-ĐTCBL V/v tăng cường kiểm tra, kiểm soát gia cầm, sản phẩm gia cầm nhập khẩu, vận chuyển trái phép qua biên giới. | Hà Nội, ngày 28 tháng 08 năm 2014
Kính gửi: | - Cục Hải quan các tỉnh, thành phố; - Cục Điều tra chống buôn lậu.
Trong thời gian gần đây, hoạt động vận chuyển, kinh doanh gia cầm, các sản phẩm gia cầm trái phép có dấu hiệu phức tạp trở lại. Nhằm chủ động trong việc đấu tranh, bắt giữ các hành vi vi phạm cũng như phòng, chống dịch cúm gia cầm lây lan qua biên giới, đặc biệt là chủng cúm gia cầm mới A/H5N6, Tổng cục Hải quan yêu cầu các đơn vị triển khai một số công việc sau
1. Quán triệt và triển khai thực hiện Công văn số 8035/BCT-QLTT ngày 20/8/2014 của Bộ Công thương (khai thác trên mạng Net Office) và các văn bản liên quan đến phòng, chống buôn lậu, vận chuyển trái phép gia cầm qua biên giới.
------------------------------------------------------------

[4] METADATA (Sẽ đẩy lên Qdrant để Filter và Rerank):
------------------------------------------------------------
{
    "article_id": "247335::preamble",
    "chapter_ref": null,
    "article_ref": "Noi dung (P1)",
    "clause_ref": null,
    "point_ref": null,
    "reference_citation": "10666/TCHQ-ĐTCBL | Noi dung (P1)",
    "is_appendix": false,
    "legal_sectors_list": [
        "Bộ máy hành chính",
        "Thương mại",
        "Xuất nhập khẩu"
    ]
}

****************************************************************************************************

====================================================================================================
 CHUNK [1] - Noi dung (P2)
====================================================================================================

[1] VĂN BẢN ĐỂ NHÚNG (Text to Embed - Vector model sẽ đọc cái này):
------------------------------------------------------------
[LEGAL HEADER]
- Title: Công văn 10666/TCHQ-ĐTCBL năm 2014 tăng cường kiểm tra, kiểm soát gia cầm, sản phẩm gia cầm nhập khẩu, vận chuyển trái phép qua biên giới do Tổng cục Hải quan ban hành
- Document number: 10666/TCHQ-ĐTCBL
- Legal type: Công văn
- Issuing authority: Tổng cục Hải quan
- Legal sectors: Bộ máy hành chính; Thương mại; Xuất nhập khẩu
- Reference tag: Noi dung (P2)
- Chapter: N/A
- Article: Noi dung (P2)
- Clause: N/A
- Point: N/A
- Is appendix: False
[NOI DUNG]
Tiếp tục thực hiện Quyết định số 2088/QĐ-TTg ngày 27/12/2012 của Thủ tướng Chính phủ về việc phê duyệt Đề án phòng ngừa, ngăn chặn vận chuyển và kinh doanh gia cầm, sản phẩm gia cầm nhập khẩu trái phép; Công văn số 1870/TCHQ-ĐTCBL ngày 10/4/2013; Công văn số 2060/TCHQ-ĐTCBL ngày 22/4/2013; Công văn số 1611/TCHQ-ĐTCBL ngày 19/02/2014 về việc tăng cường kiểm tra, kiểm soát chặt chẽ gia cầm, sản phẩm gia cầm nhập lậu, chủ động phòng, chống lây lan dịch cúm gia cầm qua biên giới; Công văn số 419/ĐTCBL-P1 ngày 03/5/2013 về việc thực hiện chế độ báo cáo nhanh đối với gia cầm, sản phẩm gia cầm nhập khẩu, vận chuyển trái phép qua biên giới bị bắt giữ, xử lý.
2. Triển khai kịp thời các chỉ đạo của Chính phủ, Bộ Tài chính, Ủy ban Nhân dân các tỉnh, thành phố, Ban chỉ đạo 389 địa phương về công tác phòng, chống buôn lậu, vận chuyển trái phép gia cầm, sản phẩm từ gia cầm qua biên giới.
3. Cục trưởng Cục Hải quan tỉnh, thành phố đôn đốc, chỉ đạo các đơn vị trực thuộc căn cứ nhiệm vụ, quyền hạn và tình hình buôn lậu trên địa bàn quản lý của đơn vị tăng cường các biện pháp nghiệp vụ kiểm soát hải quan để xác định phương thức, thủ đoạn, đường dây, ổ nhóm, đối tượng buôn bán, vận chuyển trái phép gia cầm, sản phẩm gia cầm trên địa bàn hoạt động hải quan; chủ động xây dựng kế hoạch, đấu tranh có trọng điểm, có hiệu quả, kiên quyết không để xảy ra vụ việc buôn lậu nghiêm trọng tại địa bàn quản lý của đơn vị.
------------------------------------------------------------

[2] VĂN BẢN MẢNH (Unit Text / Child Chunk):
------------------------------------------------------------
Tiếp tục thực hiện Quyết định số 2088/QĐ-TTg ngày 27/12/2012 của Thủ tướng Chính phủ về việc phê duyệt Đề án phòng ngừa, ngăn chặn vận chuyển và kinh doanh gia cầm, sản phẩm gia cầm nhập khẩu trái phép; Công văn số 1870/TCHQ-ĐTCBL ngày 10/4/2013; Công văn số 2060/TCHQ-ĐTCBL ngày 22/4/2013; Công văn số 1611/TCHQ-ĐTCBL ngày 19/02/2014 về việc tăng cường kiểm tra, kiểm soát chặt chẽ gia cầm, sản phẩm gia cầm nhập lậu, chủ động phòng, chống lây lan dịch cúm gia cầm qua biên giới; Công văn số 419/ĐTCBL-P1 ngày 03/5/2013 về việc thực hiện chế độ báo cáo nhanh đối với gia cầm, sản phẩm gia cầm nhập khẩu, vận chuyển trái phép qua biên giới bị bắt giữ, xử lý.
2. Triển khai kịp thời các chỉ đạo của Chính phủ, Bộ Tài chính, Ủy ban Nhân dân các tỉnh, thành phố, Ban chỉ đạo 389 địa phương về công tác phòng, chống buôn lậu, vận chuyển trái phép gia cầm, sản phẩm từ gia cầm qua biên giới.
3. Cục trưởng Cục Hải quan tỉnh, thành phố đôn đốc, chỉ đạo các đơn vị trực thuộc căn cứ nhiệm vụ, quyền hạn và tình hình buôn lậu trên địa bàn quản lý của đơn vị tăng cường các biện pháp nghiệp vụ kiểm soát hải quan để xác định phương thức, thủ đoạn, đường dây, ổ nhóm, đối tượng buôn bán, vận chuyển trái phép gia cầm, sản phẩm gia cầm trên địa bàn hoạt động hải quan; chủ động xây dựng kế hoạch, đấu tranh có trọng điểm, có hiệu quả, kiên quyết không để xảy ra vụ việc buôn lậu nghiêm trọng tại địa bàn quản lý của đơn vị.
------------------------------------------------------------

[3] NGỮ CẢNH ĐIỀU LUẬT (Parent Article Text - Sẽ đưa cho LLM đọc):
------------------------------------------------------------
Tiếp tục thực hiện Quyết định số 2088/QĐ-TTg ngày 27/12/2012 của Thủ tướng Chính phủ về việc phê duyệt Đề án phòng ngừa, ngăn chặn vận chuyển và kinh doanh gia cầm, sản phẩm gia cầm nhập khẩu trái phép; Công văn số 1870/TCHQ-ĐTCBL ngày 10/4/2013; Công văn số 2060/TCHQ-ĐTCBL ngày 22/4/2013; Công văn số 1611/TCHQ-ĐTCBL ngày 19/02/2014 về việc tăng cường kiểm tra, kiểm soát chặt chẽ gia cầm, sản phẩm gia cầm nhập lậu, chủ động phòng, chống lây lan dịch cúm gia cầm qua biên giới; Công văn số 419/ĐTCBL-P1 ngày 03/5/2013 về việc thực hiện chế độ báo cáo nhanh đối với gia cầm, sản phẩm gia cầm nhập khẩu, vận chuyển trái phép qua biên giới bị bắt giữ, xử lý.
2. Triển khai kịp thời các chỉ đạo của Chính phủ, Bộ Tài chính, Ủy ban Nhân dân các tỉnh, thành phố, Ban chỉ đạo 389 địa phương về công tác phòng, chống buôn lậu, vận chuyển trái phép gia cầm, sản phẩm từ gia cầm qua biên giới.
3. Cục trưởng Cục Hải quan tỉnh, thành phố đôn đốc, chỉ đạo các đơn vị trực thuộc căn cứ nhiệm vụ, quyền hạn và tình hình buôn lậu trên địa bàn quản lý của đơn vị tăng cường các biện pháp nghiệp vụ kiểm soát hải quan để xác định phương thức, thủ đoạn, đường dây, ổ nhóm, đối tượng buôn bán, vận chuyển trái phép gia cầm, sản phẩm gia cầm trên địa bàn hoạt động hải quan; chủ động xây dựng kế hoạch, đấu tranh có trọng điểm, có hiệu quả, kiên quyết không để xảy ra vụ việc buôn lậu nghiêm trọng tại địa bàn quản lý của đơn vị.
------------------------------------------------------------

[4] METADATA (Sẽ đẩy lên Qdrant để Filter và Rerank):
------------------------------------------------------------
{
    "article_id": "247335::preamble",
    "chapter_ref": null,
    "article_ref": "Noi dung (P2)",
    "clause_ref": null,
    "point_ref": null,
    "reference_citation": "10666/TCHQ-ĐTCBL | Noi dung (P2)",
    "is_appendix": false,
    "legal_sectors_list": [
        "Bộ máy hành chính",
        "Thương mại",
        "Xuất nhập khẩu"
    ]
}

****************************************************************************************************

In [ ]:
# Cell 6: config Qdrant tu .env, chunk docs va tao dense+sparse embeddings (CPU)
import time

def ensure_hybrid_collection(client: QdrantClient, collection_name: str):
    if client.collection_exists(collection_name):
        print(f"Collection already exists: {collection_name}")
        return

    client.create_collection(
        collection_name=collection_name,
        vectors_config={
            "dense": models.VectorParams(
                size=dense_dim,
                distance=models.Distance.COSINE,
                on_disk=True,
            )
        },
        sparse_vectors_config={
            "sparse": models.SparseVectorParams(
                index=models.SparseIndexParams(on_disk=False)
            )
        },
    )
    print(f"Created hybrid collection: {collection_name}")

ensure_hybrid_collection(qdrant_client, COLLECTION_NAME)

PIPELINE_STATS = {}
all_processed_chunks = []
print(f"Start chunking {len(ds_content_500)} documents...")

t_chunk_start = time.perf_counter()
for row in ds_content_500:
    doc_id = str(row["id"])
    content = row["content"]
    metadata = metadata_by_id.get(doc_id)
    if not metadata:
        continue
    all_processed_chunks.extend(chunker.process_document(content, metadata))
PIPELINE_STATS["chunk_seconds"] = time.perf_counter() - t_chunk_start

print(f"Total chunks: {len(all_processed_chunks)}")

all_texts = [chunk["text_to_embed"] for chunk in all_processed_chunks]

print("Encoding dense vectors with BGE-M3...")
batch_size = 4  # conservative default for CPU
t_dense_start = time.perf_counter()
all_dense_vectors = embedder.encode_dense(all_texts, batch_size=batch_size)
PIPELINE_STATS["dense_seconds"] = time.perf_counter() - t_dense_start

print("Encoding sparse vectors with BGE-M3 lexical weights...")
t_sparse_start = time.perf_counter()
all_sparse_vectors = sparse_encoder.encode_sparse_documents(all_texts, batch_size=batch_size)
PIPELINE_STATS["sparse_seconds"] = time.perf_counter() - t_sparse_start

PIPELINE_STATS["documents"] = len(ds_content_500)
PIPELINE_STATS["chunks"] = len(all_processed_chunks)
print("Dense + sparse vectors ready for hybrid indexing.")
print(PIPELINE_STATS)

Collection already exists: legal_rag_10000
Start chunking 500 documents...
Total chunks: 12070
Encoding dense vectors with BGE-M3...

pre tokenize: 100%|██████████| 3018/3018 [00:15<00:00, 196.56it/s]
Inference Embeddings: 100%|██████████| 3018/3018 [20:39<00:00,  2.43it/s]

Encoding sparse vectors with BGE-M3 lexical weights...

pre tokenize: 100%|██████████| 3018/3018 [00:16<00:00, 178.01it/s]
Inference Embeddings:   9%|▉         | 272/3018 [03:44<27:07,  1.69it/s]

In [ ]:
# Cell 7: build payload, upsert to Qdrant, and build payload indexes (Optimized)
import time
import uuid # <-- Bổ sung thư viện uuid

# =========================================================================
# BỔ SUNG: Kiểm tra và tạo lại Collection nếu lỡ bị xóa mất!
# =========================================================================
if not qdrant_client.collection_exists(COLLECTION_NAME):
    print(f"⚠️ Collection '{COLLECTION_NAME}' khong ton tai! Dang tao lai...")
    qdrant_client.create_collection(
        collection_name=COLLECTION_NAME,
        vectors_config={
            "dense": models.VectorParams(
                size=1024,  # Bắt buộc là 1024 cho BGE-M3
                distance=models.Distance.COSINE,
                on_disk=True,
            )
        },
        sparse_vectors_config={
            "sparse": models.SparseVectorParams(
                index=models.SparseIndexParams(on_disk=False)
            )
        },
    )
    print(f"✅ Da tao lai thanh cong Collection: {COLLECTION_NAME}")
else:
    print(f"Collection '{COLLECTION_NAME}' da ton tai.")
# =========================================================================

points_to_insert = []
t_point_build_start = time.perf_counter()

for idx, chunk in enumerate(all_processed_chunks):
    meta = chunk["metadata"]
    payload = {
        "document_id": str(meta.get("id", "")),
        "chunk_id": chunk["chunk_id"],
        "document_number": meta.get("document_number", "N/A"),
        "title": meta.get("title", "N/A"),
        "legal_type": meta.get("legal_type", "N/A"),
        "legal_sectors": meta.get("legal_sectors_list", []),
        "issuing_authority": meta.get("issuing_authority", "N/A"),
        "signer": meta.get("signer", meta.get("signers", "N/A")),
        "chapter_ref": meta.get("chapter_ref"),
        "article_id": meta.get("article_id"),
        "article_ref": meta.get("article_ref"),
        "article_title": meta.get("article_title"),
        "clause_ref": meta.get("clause_ref"),
        "point_ref": meta.get("point_ref"),
        "reference_tag": chunk["reference_tag"],
        "reference_citation": meta.get("reference_citation"),
        "is_appendix": bool(meta.get("is_appendix", False)),
        "parent_article_text": meta.get("parent_article_text", ""),
        "matched_clause_text": chunk.get("unit_text", ""),
        "chunk_text": chunk["text_to_embed"],
    }

    # Bổ sung: Tạo UUID chuẩn hóa từ chunk_id gốc để Qdrant không báo lỗi 400
    valid_qdrant_id = str(uuid.uuid5(uuid.NAMESPACE_DNS, chunk["chunk_id"]))

    point = models.PointStruct(
        id=valid_qdrant_id, # <-- Sử dụng valid_qdrant_id tại đây
        vector={
            "dense": all_dense_vectors[idx],
            "sparse": all_sparse_vectors[idx],
        },
        payload=payload,
    )
    points_to_insert.append(point)

PIPELINE_STATS["point_build_seconds"] = time.perf_counter() - t_point_build_start

BATCH_UPSERT = 100
print(f"Upserting {len(points_to_insert)} hybrid points to Qdrant Docker...")

t_upsert_start = time.perf_counter()
for start in range(0, len(points_to_insert), BATCH_UPSERT):
    batch = points_to_insert[start : start + BATCH_UPSERT]
    qdrant_client.upsert(
        collection_name=COLLECTION_NAME,
        points=batch,
        wait=True,
    )
PIPELINE_STATS["upsert_seconds"] = time.perf_counter() - t_upsert_start

print(f"Done upsert {len(points_to_insert)} points to collection {COLLECTION_NAME}.")

def safe_create_payload_index(client, collection_name, field_name, field_schema):
    try:
        client.create_payload_index(
            collection_name=collection_name,
            field_name=field_name,
            field_schema=field_schema,
            wait=True,
        )
        print(f"[index] Created: {field_name}")
    except Exception as exc:
        print(f"[index] Skipped/Exists: {field_name} - {exc}")

print("\n--- Setting up Payload Indexes ---")
# 1. Nhóm Định vị (Exact Match)
for field in ["document_id", "document_number", "chapter_ref", "article_ref", "clause_ref", "point_ref"]:
    safe_create_payload_index(qdrant_client, COLLECTION_NAME, field, models.PayloadSchemaType.KEYWORD)

# 2. Nhóm Phân loại
for field in ["legal_type", "legal_sectors", "issuing_authority", "signer"]:
    safe_create_payload_index(qdrant_client, COLLECTION_NAME, field, models.PayloadSchemaType.KEYWORD)

# 3. Nhóm Cờ trạng thái
safe_create_payload_index(qdrant_client, COLLECTION_NAME, "is_appendix", models.PayloadSchemaType.BOOL)

# 4. Nhóm Tiêu đề (Searchable Text - Vietnamese Optimized)
safe_create_payload_index(
    qdrant_client,
    COLLECTION_NAME,
    "title",
    models.TextIndexParams(
        type="text",
        tokenizer=models.TokenizerType.WORD,
        min_token_len=2,
        max_token_len=20,
        lowercase=True,
    )
)

# 5. Cấu hình Quantization (Nén int8)
try:
    qdrant_client.update_collection(
        collection_name=COLLECTION_NAME,
        quantization_config=models.ScalarQuantization(
            scalar=models.ScalarQuantizationConfig(
                type="int8",
                quantile=0.99,
                always_ram=True,
            )
        ),
    )
    print("\n[Quantization] Enabled ScalarQuantization int8 for dense vectors.")
except Exception as exc:
    print(f"\n[Quantization] Skip update: {exc}")

total_measured = sum(PIPELINE_STATS.get(k, 0.0) for k in ["chunk_seconds", "dense_seconds", "sparse_seconds", "point_build_seconds", "upsert_seconds"])
PIPELINE_STATS["total_seconds_measured"] = total_measured
print("\nPIPELINE_STATS:", PIPELINE_STATS)

In [ ]:
# CPU runtime estimate based on measured pipeline stats
import math

if not PIPELINE_STATS:
    print("PIPELINE_STATS is empty. Please run Cell 6 and Cell 7 first.")
else:
    measured_docs = max(int(PIPELINE_STATS.get("documents", 0)), 1)
    measured_chunks = max(int(PIPELINE_STATS.get("chunks", 0)), 1)

    t_chunk = float(PIPELINE_STATS.get("chunk_seconds", 0.0))
    t_dense = float(PIPELINE_STATS.get("dense_seconds", 0.0))
    t_sparse = float(PIPELINE_STATS.get("sparse_seconds", 0.0))
    t_point_build = float(PIPELINE_STATS.get("point_build_seconds", 0.0))
    t_upsert = float(PIPELINE_STATS.get("upsert_seconds", 0.0))
    t_total = float(PIPELINE_STATS.get("total_seconds_measured", 0.0))

    sec_per_doc = t_total / measured_docs
    sec_per_chunk = t_total / measured_chunks

    for target_docs in [100, 500, 1000, 10000]:
        est_seconds = sec_per_doc * target_docs
        est_minutes = est_seconds / 60.0
        est_hours = est_minutes / 60.0
        print(
            f"Estimate for {target_docs:>5} docs: "
            f"{est_seconds:,.1f}s | {est_minutes:,.1f}m | {est_hours:,.2f}h"
        )

    print("\nMeasured breakdown on CPU:")
    print(f"- chunking:     {t_chunk:,.2f}s")
    print(f"- dense embed:  {t_dense:,.2f}s")
    print(f"- sparse embed: {t_sparse:,.2f}s")
    print(f"- point build:  {t_point_build:,.2f}s")
    print(f"- upsert:       {t_upsert:,.2f}s")
    print(f"- total:        {t_total:,.2f}s")
    print(f"- avg/doc:      {sec_per_doc:,.3f}s")
    print(f"- avg/chunk:    {sec_per_chunk:,.3f}s")

In [ ]:
# Cell 8: Native Hybrid Legal Retrieval -> Payload Filtering + BGE-M3 + Native RRF
from qdrant_client import models
from typing import List, Optional, Any


def detect_sector_hints(query: str, hot_sectors: List[str]) -> List[str]:
    lowered = query.lower()
    hits = [sector for sector in hot_sectors if sector.lower() in lowered]
    return hits[:3]


class LegalHybridRetriever:
    def __init__(
        self,
        client: QdrantClient,
        collection_name: str,
        hybrid_encoder: Any,
        hot_sectors: List[str],
    ):
        self.client = client
        self.collection_name = collection_name
        self.hybrid_encoder = hybrid_encoder
        self.hot_sectors = hot_sectors

    def build_filter(
        self,
        query: str,
        is_appendix: Optional[bool] = None,
        legal_type: Optional[str] = None,
        doc_number: Optional[str] = None,
    ):
        must_conditions = []
        should_conditions = []

        if is_appendix is not None:
            must_conditions.append(
                models.FieldCondition(
                    key="is_appendix",
                    match=models.MatchValue(value=is_appendix),
                )
            )
        if legal_type:
            must_conditions.append(
                models.FieldCondition(
                    key="legal_type",
                    match=models.MatchValue(value=legal_type),
                )
            )
        if doc_number:
            must_conditions.append(
                models.FieldCondition(
                    key="document_number",
                    match=models.MatchValue(value=doc_number),
                )
            )

        # Sector filter: kiem tra sector co nam trong mang payload legal_sectors hay khong
        for sector in detect_sector_hints(query, self.hot_sectors):
            should_conditions.append(
                models.FieldCondition(
                    key="legal_sectors",
                    match=models.MatchValue(value=sector),
                )
            )
            should_conditions.append(
                models.FieldCondition(
                    key="title",
                    match=models.MatchText(text=sector),
                )
            )

        if not must_conditions and not should_conditions:
            return None

        return models.Filter(
            must=must_conditions or None,
            should=should_conditions or None,
        )

    def search(
        self,
        query: str,
        limit: int = 5,
        is_appendix: Optional[bool] = None,
        legal_type: Optional[str] = None,
        doc_number: Optional[str] = None,
    ):
        query_filter = self.build_filter(
            query=query,
            is_appendix=is_appendix,
            legal_type=legal_type,
            doc_number=doc_number,
        )

        dense_query = self.hybrid_encoder.encode_dense([query], batch_size=1)[0]
        sparse_query = self.hybrid_encoder.encode_query_sparse(query)

        prefetch_limit = max(limit * 3, 10)

        hits = self.client.query_points(
            collection_name=self.collection_name,
            prefetch=[
                models.Prefetch(
                    query=dense_query,
                    using="dense",
                    limit=prefetch_limit,
                    filter=query_filter,
                ),
                models.Prefetch(
                    query=sparse_query,
                    using="sparse",
                    limit=prefetch_limit,
                    filter=query_filter,
                )
            ],
            query=models.FusionQuery(fusion=models.Fusion.RRF),
            limit=max(limit * 2, 10),
            with_payload=True,
        ).points

        dedup_results = []
        seen_articles = set()

        for hit in hits:
            payload = hit.payload
            article_id = payload.get("article_id") or payload.get("chunk_id")
            if article_id in seen_articles:
                continue
            seen_articles.add(article_id)

            dedup_results.append({
                "id": hit.id,
                "payload": payload,
                "rrf_score": hit.score,
                "dense_score": "Native Fusion",
                "sparse_score": "Native Fusion",
            })
            if len(dedup_results) >= limit:
                break

        return dedup_results


def print_retrieval_results(results):
    if not results:
        print("Khong tim thay ket qua phu hop.")
        return

    for idx, item in enumerate(results, start=1):
        payload = item["payload"]
        matched_clause = (payload.get("matched_clause_text") or "").replace("\n", " ")
        parent_article = (payload.get("parent_article_text") or "").replace("\n", " ")
        sectors = payload.get("legal_sectors") or []
        print(
            f"[{idx}] RRF_Score={item['rrf_score']:.4f} | Qdrant Native Fusion"
        )
        print(f"    Title: {payload.get('title')}")
        print(f"    Citation: {payload.get('reference_citation')}")
        print(f"    Appendix: {payload.get('is_appendix')} | Sectors: {sectors}")
        print(f"    Matched clause: {matched_clause[:260]}...")
        print(f"    Full article preview: {parent_article[:260]}...")
        print("-" * 140)


retriever = LegalHybridRetriever(
    client=qdrant_client,
    collection_name=COLLECTION_NAME,
    hybrid_encoder=hybrid_encoder,
    hot_sectors=HOT_SECTORS,
)


def legal_retrieval(
    query: str,
    limit: int = 5,
    is_appendix: Optional[bool] = None,
    legal_type: Optional[str] = None,
    doc_number: Optional[str] = None,
):
    print(f"TRUY VAN: {query}")
    results = retriever.search(
        query=query,
        limit=limit,
        is_appendix=is_appendix,
        legal_type=legal_type,
        doc_number=doc_number,
    )
    print_retrieval_results(results)
    return results

In [ ]:
"""
LLM adapter for notebook (Standalone - No core/ dependencies needed).
"""
from collections import defaultdict
from typing import List, Dict
import os
from openai import OpenAI

# Khởi tạo Mock/Dummy cho OpenAI/Groq (Sẽ tạo lại nếu query)
def _get_openai_client():
    return OpenAI(
        api_key=os.environ.get("OPENAI_API_KEY") or os.environ.get("GROQ_API_KEY") or "dummy",
        base_url=os.environ.get("LLM_BASE_URL", "https://api.groq.com/openai/v1"),
    )

_gemini_client = None
def _get_gemini_client():
    global _gemini_client
    if _gemini_client is None:
        from google import genai
        _gemini_client = genai.Client(api_key=os.environ.get("GEMINI_API_KEY", ""))
    return _gemini_client

def repo_chat_completion(
    messages: List[Dict[str, str]],
    temperature: float = 0.3,
    provider: str = None,
    model: str = None,
) -> str:
    provider = (provider or os.environ.get("LLM_PROVIDER", "groq")).lower()

    if provider == "gemini":
        from google.genai import types as genai_types
        client = _get_gemini_client()
        system_instruction = None
        contents = []
        for m in messages:
            role = m["role"]
            if role == "system":
                system_instruction = m["content"]
            else:
                gemini_role = "model" if role == "assistant" else "user"
                contents.append(
                    genai_types.Content(
                        role=gemini_role,
                        parts=[genai_types.Part(text=m["content"])],
                    )
                )
        config = genai_types.GenerateContentConfig(
            temperature=temperature,
            system_instruction=system_instruction,
        )
        response = client.models.generate_content(
            model=model or "gemini-2.5-flash",
            contents=contents,
            config=config,
        )
        return response.text

    # Mặc định (Groq, OpenAI)
    client = _get_openai_client()
    response = client.chat.completions.create(
        model=model or "llama-3.3-70b-versatile",
        messages=messages,
        temperature=temperature,
    )
    return response.choices[0].message.content

In [ ]:
# Cell 9: LLM wrapper + memory 5 turn + rewrite query + augment/generation
class SessionMemory:
    def __init__(self, max_turns: int = 5):
        self.max_turns = max_turns
        self.sessions = defaultdict(list)

    def get_history(self, session_id: str):
        return self.sessions.get(session_id, [])

    def add_message(self, session_id: str, role: str, content: str):
        self.sessions[session_id].append({"role": role, "content": content})
        max_messages = self.max_turns * 2
        if len(self.sessions[session_id]) > max_messages:
            self.sessions[session_id] = self.sessions[session_id][-max_messages:]


class NotebookLegalLLM:
    def __init__(self, provider: str = "mock", model_name: Optional[str] = None):
        self.provider = provider
        self.model_name = model_name or os.getenv(
            "NOTEBOOK_LLM_MODEL",
            "meta-llama/Meta-Llama-3.1-8B-Instruct",
        )
        self.generator = None

    def _load_local_generator(self):
        if self.generator is None:
            import torch
            from transformers import pipeline

            torch_dtype = torch.float16 if torch.cuda.is_available() else torch.float32
            self.generator = pipeline(
                "text-generation",
                model=self.model_name,
                device_map="auto" if torch.cuda.is_available() else None,
                torch_dtype=torch_dtype,
            )
        return self.generator

    def generate_text(
        self,
        messages: List[Dict[str, str]],
        temperature: float = 0.2,
        max_new_tokens: int = 512,
    ) -> str:
        if self.provider == "repo_api" and repo_chat_completion is not None:
            return repo_chat_completion(messages=messages, temperature=temperature)

        if self.provider == "local_llama":
            generator = self._load_local_generator()
            prompt = "\n\n".join(
                [f"{msg['role'].upper()}: {msg['content']}" for msg in messages]
            ) + "\nASSISTANT:"
            output = generator(
                prompt,
                max_new_tokens=max_new_tokens,
                do_sample=temperature > 0,
                temperature=max(temperature, 0.1),
                return_full_text=False,
            )[0]["generated_text"]
            return output.strip()

        return ""

    def rewrite_query(self, history: List[Dict[str, str]], current_query: str) -> str:
        if not history:
            return current_query

        if self.provider in {"repo_api", "local_llama"}:
            history_text = "\n".join(
                [f"{message['role']}: {message['content']}" for message in history]
            )
            rewrite_prompt = (
                "Viet lai cau hoi hien tai thanh mot standalone query phap ly bang tieng Viet.\n"
                f"Lich su hoi dap:\n{history_text}\n\n"
                f"Cau hoi hien tai: {current_query}\n\n"
                "Chi tra ve cau query da viet lai."
            )
            rewritten = self.generate_text(
                [{"role": "user", "content": rewrite_prompt}],
                temperature=0.0,
                max_new_tokens=128,
            )
            return rewritten or current_query

        recent_user_turns = [m["content"] for m in history if m["role"] == "user"][-2:]
        if recent_user_turns:
            return " | ".join(recent_user_turns + [current_query])
        return current_query

    def answer_from_context(
        self,
        user_query: str,
        rewritten_query: str,
        mode: str,
        results: List[Dict[str, Any]],
    ) -> str:
        if not results:
            return "Chua tim thay ngu canh phu hop trong kho du lieu de tra loi cau hoi nay."

        if self.provider in {"repo_api", "local_llama"}:
            context_blocks = []
            for idx, item in enumerate(results[:4], start=1):
                payload = item["payload"]
                context_blocks.append(
                    f"[{idx}] {payload.get('reference_citation')}\n"
                    f"Title: {payload.get('title')}\n"
                    f"Full article:\n{payload.get('parent_article_text')}\n"
                    f"Matched clause:\n{payload.get('matched_clause_text')}\n"
                )

            system_prompt = (
                "Ban la tro ly phap ly Viet Nam. "
                "Chi duoc dua tren CONTEXT va phai trich dan dieu-khoan-diem neu co."
            )
            user_prompt = (
                f"[MODE]: {mode}\n"
                f"[QUERY_GOC]: {user_query}\n"
                f"[QUERY_DA_VIET_LAI]: {rewritten_query}\n\n"
                f"[CONTEXT]\n{chr(10).join(context_blocks)}\n\n"
                "Tra loi ro rang, ngan gon, va tach rieng muc Can cu phap ly."
            )
            generated = self.generate_text(
                [
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=0.2,
                max_new_tokens=512,
            )
            if generated:
                return generated

        if mode == "sector_search":
            lines = [
                f"Tim thay {len(results)} ket qua lien quan den truy van: {rewritten_query}",
                "",
            ]
            for idx, item in enumerate(results[:5], start=1):
                payload = item["payload"]
                lines.append(
                    f"{idx}. {payload.get('title')} | {payload.get('reference_citation')} | "
                    f"Linh vuc: {payload.get('legal_sectors', [])}"
                )
            return "\n".join(lines)

        top_payload = results[0]["payload"]
        lines = [
            f"Tra loi so bo cho cau hoi: {user_query}",
            "",
            (top_payload.get("matched_clause_text") or top_payload.get("parent_article_text", ""))[:900],
            "",
            "Can cu phap ly:",
        ]
        for item in results[:3]:
            payload = item["payload"]
            lines.append(f"- {payload.get('reference_citation')}")
        return "\n".join(lines)


class LegalChatAssistant:
    def __init__(self, retriever: LegalHybridRetriever, llm: NotebookLegalLLM, max_turns: int = 5):
        self.retriever = retriever
        self.llm = llm
        self.memory = SessionMemory(max_turns=max_turns)

    def ask(
        self,
        session_id: str,
        query: str,
        mode: str = "knowledge_qa",
        limit: int = 5,
        is_appendix: Optional[bool] = None,
        legal_type: Optional[str] = None,
        doc_number: Optional[str] = None,
    ):
        history = self.memory.get_history(session_id)
        rewritten_query = self.llm.rewrite_query(history, query)
        retrieval_results = self.retriever.search(
            query=rewritten_query,
            limit=limit,
            is_appendix=is_appendix,
            legal_type=legal_type,
            doc_number=doc_number,
        )
        answer = self.llm.answer_from_context(
            user_query=query,
            rewritten_query=rewritten_query,
            mode=mode,
            results=retrieval_results,
        )

        self.memory.add_message(session_id, "user", query)
        self.memory.add_message(session_id, "assistant", answer)

        return {
            "answer": answer,
            "rewritten_query": rewritten_query,
            "results": retrieval_results,
        }


# Đổi thẳng provider thành "repo_api" để kích hoạt hàm repo_chat_completion (hỗ trợ gọi API)
NOTEBOOK_LLM_PROVIDER = "repo_api"
# Bắt buộc LLM_PROVIDER phải là "gemini" để code biết cần gọi thư viện nào
os.environ["LLM_PROVIDER"] = "gemini"

legal_llm = NotebookLegalLLM(provider=NOTEBOOK_LLM_PROVIDER)
assistant = LegalChatAssistant(retriever=retriever, llm=legal_llm, max_turns=5)

print(f"Notebook LLM provider: {NOTEBOOK_LLM_PROVIDER} (Sử dụng {os.environ.get('LLM_PROVIDER')})")

In [ ]:
# Cell 10: DEMO TỔNG HỢP CÁC TÍNH NĂNG CỦA LEGAL-RAG
print("=" * 140)
print("PHẦN 1: TRUY VẤN VECTOR THUẦN TÚY (SMART RETRIEVAL)")
print("=" * 140)
legal_retrieval(
    query="Quy định về cơ cấu tổ chức và nguyên tắc hoạt động của chính quyền địa phương",
    limit=3,
    is_appendix=None,
)

print("\n" + "=" * 140)
print("PHẦN 2: DEMO LLM CHATBOT PHÁP LÝ (3 KỊCH BẢN THỰC TẾ)")
print("=" * 140)

# =====================================================================
# KỊCH BẢN 1: HỎI ĐÁP PHÁP LÝ (Knowledge QA)
# Chức năng: Đưa ra câu trả lời trực tiếp kèm căn cứ pháp lý.
# =====================================================================
print("\n[KỊCH BẢN 1] - HỎI ĐÁP KIẾN THỨC PHÁP LÝ")
print("-" * 50)
qa_response = assistant.ask(
    session_id="qa_session_01",
    query="Nguyên tắc quản lý ngân sách nhà nước và các khoản thu ngân sách được quy định như thế nào?",
    mode="knowledge_qa",
    limit=4,
)
print(f"🗣️ User: Nguyên tắc quản lý ngân sách nhà nước và các khoản thu ngân sách được quy định như thế nào?")
print(f"🤖 AI Answer:\n{qa_response['answer']}")
print("\n📚 Trích dẫn top đầu:")
for item in qa_response["results"][:2]:
    print(f"   - {item['payload'].get('reference_citation')}")


# =====================================================================
# KỊCH BẢN 2: TÌM KIẾM TÀI LIỆU (Sector Search)
# Chức năng: Đóng vai trò thư viện viên, tổng hợp danh sách văn bản.
# =====================================================================
print("\n\n[KỊCH BẢN 2] - TÌM KIẾM VÀ TỔNG HỢP TÀI LIỆU")
print("-" * 50)
search_response = assistant.ask(
    session_id="search_session_01",
    query="Hãy liệt kê cho tôi danh sách các văn bản quy định về quản lý Thuế và Lệ phí.",
    mode="sector_search",
    limit=5,
)
print(f"🗣️ User: Hãy liệt kê cho tôi danh sách các văn bản quy định về quản lý Thuế và Lệ phí.")
print(f"🤖 AI Answer:\n{search_response['answer']}")


# =====================================================================
# KỊCH BẢN 3: CHAT DÀI HẠN (Multi-turn Memory)
# Chức năng: Giữ nguyên session_id, hỏi nối tiếp để test tính năng Query Rewrite.
# =====================================================================
print("\n\n[KỊCH BẢN 3] - CHAT DÀI HẠN (NHỚ NGỮ CẢNH ĐỂ SUY LUẬN)")
print("-" * 50)

chat_turns = [
    "Thủ tục kê khai thuế giá trị gia tăng (GTGT) được thực hiện như thế nào?",
    "Thời hạn nộp hồ sơ cho thủ tục trên là ngày mùng mấy hàng tháng?",
    "Nếu tôi nộp chậm báo cáo đó thì có bị phạt không? Mức phạt là bao nhiêu?",
    "Vậy có trường hợp nào được miễn phạt vi phạm hành chính đối với khoản trên không?"
]

# Lưu ý: Tất cả các lượt hỏi đều dùng chung session_id="long_chat_session"
for i, turn_query in enumerate(chat_turns, 1):
    print(f"\n--- LƯỢT CHAT THỨ {i} ---")
    resp = assistant.ask(
        session_id="long_chat_session",
        query=turn_query,
        mode="knowledge_qa",
        limit=3,
    )
    print(f"🗣️ User hỏi: {turn_query}")
    print(f"🧠 AI tự viết lại câu hỏi để Query Vector: {resp['rewritten_query']}")
    print(f"🤖 AI Trả lời:\n{resp['answer']}")